name: Build and Run Cloud Run Job

on:
  workflow_dispatch:
    inputs:
      check_path:
        description: 'SQL Update User Account Privileges'
        required: false
        default: 'config.py'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: apigee-test-0002-demo

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build and Push Image to GCR
        run: |
          gcloud builds submit \
            --tag gcr.io/apigee-test-0002-demo/sql-update-user-privileges

      - name: Deploy Cloud Run Job with secrets and VPC
        run: |
          gcloud run jobs deploy sql-update-user-privileges-job \
            --image gcr.io/apigee-test-0002-demo/sql-update-user-privileges \
            --region us-central1 \
            --project apigee-test-0002-demo \
            --execution-environment gen2 \
            --service-account 741169614600-compute@developer.gserviceaccount.com \
            --vpc-connector projects/apigee-test-0002-demo/locations/us-central1/connectors/YOUR_VPC_CONNECTOR_NAME \
            --set-secrets=\
PGSSLCERT=pg-client-cert:latest,\
PGSSLKEY=pg-client-private-key:latest,\
PGSSLROOTCERT=pg-server-ca-cert:latest,\
PGPASSWORD=pg-app-user-password:latest,\
COMMUNICATION_CSV_DB=communication_csv_db:latest \
            --set-env-vars=\
PGSSLCERT=/secrets/client-cert/client-cert.pem,\
PGSSLKEY=/secrets/client-key/client-key.pem,\
PGSSLROOTCERT=/secrets/server-ca/server-ca.pem,\
PGPASSWORD=/secrets/admin-password/pg-admin-user-password \
            --args "main.py"
