name: Run Cloud Run Job

on:
  workflow_dispatch:
    inputs:
      check_path:
        description: 'SQL Update User Account Privileges'
        required: false
        default: 'config.py'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: apigee-test-0002-demo

      - name: Deploy Cloud Run Job
        run: |
          PROJECT=apigee-test-0002-demo
          JOB_NAME=sql-connectivity-checks-job
          IMAGE_URI=gcr.io/$PROJECT/sql-connectivity-check
          REGION=us-central1
          VPC_CONNECTOR=projects/$PROJECT/locations/$REGION/connectors/cloud-run-vpc-connector
      
          SECRET_DB_PASSWORD=pg-admin-user-password
          SECRET_SSL_CERT=pg-client-cert
          SECRET_SSL_KEY=pg-client-private-key
          SECRET_SSL_ROOTCERT=pg-server-ca-cert
      
          # Clear the wrongly set environment variables
          gcloud run jobs update $JOB_NAME \
            --region $REGION \
            --clear-secrets DB_SSL_CERT,DB_SSL_KEY,DB_SSL_ROOTCERT
          
          # Now set them correctly as secrets (mounted as files)
          gcloud run jobs update $JOB_NAME \
            --region $REGION \
            --image $IMAGE_URI \
            --vpc-connector $VPC_CONNECTOR \
            --set-env-vars DB_HOST=10.15.68.5,DB_PORT=5432,DB_NAME=testdb,DB_USER=pgadmin \
            --set-secrets DB_PASSWORD=pg-admin-user-password:latest \
            --set-secrets DB_SSL_CERT=pg-client-cert:latest \
            --set-secrets DB_SSL_KEY=pg-client-private-key:latest \
            --set-secrets DB_SSL_ROOTCERT=pg-server-ca-cert:latest


