name: Run Cloud Run Job

on:
  workflow_dispatch:
    inputs:
      check_path:
        description: 'SQL Update User Account Privileges'
        required: false
        default: 'config.py'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: apigee-test-0002-demo

      - name: Deploy Cloud Run Job
        run: |
          PROJECT=apigee-test-0002-demo
          JOB_NAME=sql-connectivity-checks-job
          IMAGE_URI=gcr.io/$PROJECT/sql-connectivity-check
          REGION=us-central1
          VPC_CONNECTOR=projects/$PROJECT/locations/$REGION/connectors/cloud-run-vpc-connector
          DB_PRIVATE_IP=10.15.68.5
      
          # Delete job if it exists
          if gcloud run jobs describe $JOB_NAME --region $REGION --project $PROJECT >/dev/null 2>&1; then
            echo "🔄 Job $JOB_NAME exists — deleting..."
            gcloud run jobs delete $JOB_NAME --region $REGION --project $PROJECT --quiet
          fi
      
          # Create new job with secrets as env vars
          gcloud run jobs create $JOB_NAME \
            --image $IMAGE_URI \
            --region $REGION \
            --vpc-connector $VPC_CONNECTOR \
            --set-env-vars DB_HOST=10.15.68.5,DB_PORT=5432,DB_NAME=testdb,DB_USER=pgadmin,DB_SSLMODE=require \
            --set-secrets DB_PASSWORD=pg-admin-user-password:latest \
            --set-secrets DB_SSL_CERT=pg-client-cert:latest \
            --set-secrets DB_SSL_KEY=pg-client-private-key:latest \
            --set-secrets DB_SSL_ROOTCERT=pg-server-ca-cert:latest \
            --execute-now






