name: Build and Run Cloud Run Job

on:
  workflow_dispatch:
    inputs:
      check_path:
        description: 'SQL Update User Account Privileges'
        required: false
        default: 'config.py'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: apigee-test-0002-demo

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build and Push Image to GCR
        run: |
          gcloud builds submit \
            --tag gcr.io/apigee-test-0002-demo/sql-update-user-privileges

      - name: Deploy Cloud Run Job
        run: |
          JOB_NAME=sql-update-user-privileges-job
          IMAGE_URI=gcr.io/apigee-test-0002-demo/sql-update-user-privileges
          REGION=us-central1
          PROJECT=apigee-test-0002-demo
          SERVICE_ACCOUNT=741169614600-compute@developer.gserviceaccount.com
          VPC_CONNECTOR=projects/$PROJECT/locations/$REGION/connectors/cloud-run-vpc-connector

          gcloud run jobs deploy $JOB_NAME \
            --project $PROJECT \
            --image $IMAGE_URI \
            --region $REGION \
            --service-account $SERVICE_ACCOUNT \
            --execution-environment gen2 \
            --vpc-connector $VPC_CONNECTOR \
            --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT \
            --command "python" \
            --args "main.py"
            
      - name: Execute Cloud Run Job
        run: |
          gcloud run jobs execute sql-update-user-privileges-job \
            --region us-central1
